local win = vim.api.nvim_get_current_win()
local ns = vim.api.nvim_create_namespace("qf_highlight_" .. win)

vim.api.nvim_set_hl(ns, "QfTypeError", {link = "Error", bold = true})
vim.api.nvim_set_hl(ns, "QfTypeWarning", {link = "WarningMsg", bold = true})
vim.api.nvim_set_hl(ns, "QfTypeOther", {link = "Debug", bold = true})
vim.api.nvim_set_hl(ns, "QfUnknown", {link = "Comment"})
vim.api.nvim_set_hl(ns, "QfFile", {link = "String"})
vim.api.nvim_set_hl(ns, "QfDelimiter", {link = "Delimiter"})
vim.api.nvim_set_hl(ns, "QfNumber", {link = "Number"})
vim.api.nvim_set_hl(ns, "QfMessage", {link = "MsgArea"})
vim.api.nvim_win_set_hl_ns(win, ns)

vim.fn.matchadd("QfLine", [[.]], 10, -1, {window = win})
vim.fn.matchadd("QfTypeOther", [[^\w*]], 10, -1, {window = win})
vim.fn.matchadd("QfTypeWarning", [[^W\w*]], 10, -1, {window = win})
vim.fn.matchadd("QfTypeError", [[^E\w*]], 10, -1, {window = win})
vim.fn.matchadd("QfFile", [[^\w\+\s\+\zs.\{-}\ze:]], 10, -1, {window = win})
vim.fn.matchadd("QfNumber", [[\d]], 10, -1, {window = win})
vim.fn.matchadd("QfDelimiter", [[:]], 10, -1, {window = win})
vim.fn.matchadd("QfMessage", [[^.*:\d*:\d*:\s*\zs.*\ze]], 10, -1, {window = win})
vim.fn.matchadd("QfUnknown", [[^│.*]], 10, -1, {window = win})
